// Downloads the woff2 files the site actually uses into site/fonts/ and writes
// the matching @font-face rules to site/css/fonts.css.
//
// Self-hosted rather than linked from fonts.googleapis.com: that link is a
// render-blocking request to a third party, and next/font was self-hosting
// these already — switching to the CDN would have been a regression.
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const FONT_DIR = path.join(ROOT, "site", "fonts");
const CSS_OUT = path.join(ROOT, "site", "css", "fonts.css");

// Playfair Display (headings + italic emphasis words within them) and
// Space Grotesk (nav/labels/body/buttons) — pulled from the Variant concept
// reference Mike sent (2026-07-23), replacing Roboto Condensed / IBM Plex
// Mono site-wide.
const FACES = [
  { family: "Playfair Display", weight: 400, style: "normal" },
  { family: "Playfair Display", weight: 700, style: "normal" },
  { family: "Playfair Display", weight: 400, style: "italic" },
  { family: "Space Grotesk", weight: 400, style: "normal" },
  { family: "Space Grotesk", weight: 500, style: "normal" },
  { family: "Space Grotesk", weight: 600, style: "normal" },
  { family: "Space Grotesk", weight: 700, style: "normal" },
];

// A modern-browser UA so Google serves woff2 rather than ttf.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";

await mkdir(FONT_DIR, { recursive: true });
await mkdir(path.dirname(CSS_OUT), { recursive: true });

const blocks = [];

for (const face of FACES) {
  const ital = face.style === "italic" ? 1 : 0;
  const fam = face.family.replace(/ /g, "+");
  const url = `https://fonts.googleapis.com/css2?family=${fam}:ital,wght@${ital},${face.weight}&display=swap`;

  const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => r.text());

  // Keep only the latin block — the site is English-only, and pulling every
  // subset would multiply the payload for glyphs that never render.
  const latin = css.split("/* latin */")[1];
  if (!latin) throw new Error(`no latin subset for ${face.family} ${face.weight} ${face.style}`);

  const src = latin.match(/src:\s*url\(([^)]+)\)/)?.[1];
  const unicodeRange = latin.match(/unicode-range:\s*([^;]+);/)?.[1];
  if (!src) throw new Error(`no woff2 url for ${face.family} ${face.weight} ${face.style}`);

  const slug = `${face.family.toLowerCase().replace(/ /g, "-")}-${face.weight}${
    face.style === "italic" ? "-italic" : ""
  }.woff2`;

  const buf = Buffer.from(await (await fetch(src)).arrayBuffer());
  await writeFile(path.join(FONT_DIR, slug), buf);
  console.log(`  ${slug.padEnd(38)} ${(buf.length / 1024).toFixed(0)}KB`);

  blocks.push(
    `@font-face {
  font-family: "${face.family}";
  font-style: ${face.style};
  font-weight: ${face.weight};
  font-display: swap;
  src: url("../fonts/${slug}") format("woff2");
  unicode-range: ${unicodeRange};
}`,
  );
}

await writeFile(
  CSS_OUT,
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.
   Latin subset only; the site is English-only. */\n\n${blocks.join("\n\n")}\n`,
);
console.log(`\n  wrote ${path.relative(ROOT, CSS_OUT)}`);
